apiVersion: v1
kind: Service
metadata:
    name: http-service
    labels:
        name: httpservice
spec:
    type: NodePort
    selector:
        app: httpapp
    ports:
        - protocol: TCP
          nodePort: 30307
          port: 9100
          targetPort: 9100