apiVersion: v1
kind: Service
metadata:
    name: http-xorm-service
    labels:
        name: http-xorm-service
spec:
    type: NodePort
    selector:
        app: httpxorm
    ports:
        - protocol: TCP
          nodePort: 30308
          port: 9101
          targetPort: 9101